<?php include 'cabecalho.phtml'; ?>
<?php include 'menu.phtml'; ?>

<br />
<br />
<br />

<div class="container">
	<div id="loginbox" style="margin-top: 50px;"
		class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">

		<?php if (!esta_logado()) { ?>

		<div class="panel panel-info">
			<div class="panel-heading">
				<div class="panel-title">Entrar na &aacute;rea restrita</div>
				<!--
				<div
					style="float: right; font-size: 80%; position: relative; top: -10px">
					<a href="#">Esqueceu a senha?</a>
				</div>
				 -->
			</div>

			<div style="padding-top: 30px" class="panel-body">

				<div style="display: none" id="login-alert"	class="alert alert-danger col-sm-12"></div>

				<form  action="entrar/entrou"  id="loginform" class="form-horizontal"  method="post" role="form">

					<div style="margin-bottom: 25px" class="input-group">
						<span class="input-group-addon">
						  <i class="glyphicon glyphicon-user"></i></span> <input
							id="login-username" type="text" class="form-control"
							name="username" value="" placeholder="usu&aacute;rio">
					</div>

					<div style="margin-bottom: 25px" class="input-group">
						<span class="input-group-addon"><i
							class="glyphicon glyphicon-lock"></i></span> <input
							id="login-password" type="password" class="form-control"
							name="password" placeholder="senha">
					</div>

					<div style="margin-top: 10px" class="form-group">
						<div class="col-sm-12 controls">
							<a id="btn-login" href="javascript:document.getElementById('loginform').submit()" class="btn btn-success">Entrar </a>
						</div>
					</div>
				</form>

			</div>
		</div>

		<?php }  ?>
	  </div>
	</div>

<?php include 'rodape.phtml'; ?>