
<?php include 'cabecalho.phtml'; ?>
<?php include 'menu.phtml'; ?>

    <div class="container">
     <br/><br/><br/><br/>
      <div class="jumbotron">
        <h2>Sofia PHP</h2>
        <p>
          <a class="btn btn-lg btn-primary" href="#" role="button">Em portugu&ecirc;s</a>
          <a class="btn btn-lg btn-primary" href="#" role="button">Layout com Bootstrap</a>
          <a class="btn btn-lg btn-primary" href="#" role="button">Olhe o c&oacute;digo fonte!</a>
        </p>
      </div>

    </div>

<?php include 'rodape.phtml'; ?>
