    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only"> </span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
             <a class="dropdown-toggle" data-toggle="dropdown" href="#">Sofia PHP<b class="caret"></b></a>
              <ul class="dropdown-menu">
                 <li><a href="<?php echo $servidor ?>/sofia">Vers&atilde;o do sistema</a></li>
              </ul>
            </li>
            <li class="dropdown">
	           <?php if (!esta_logado()) { ?>
	            <a href="<?php echo $servidor ?>/entrar">Entrar na &aacute;rea restrita</a></li>
	           <?php } else { ?>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo bem_vindo() ?> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                 <li><a href="<?php echo $servidor ?>/sair">Sair</a></li>
                </ul>
	           <?php } ?>
             </li>
          <li><a href="#">Op&ccedil;&atilde;o 1</a></li>
          <li><a href="#">Op&ccedil;&atilde;o 2</a></li>
          <li><a href="#">Op&ccedil;&atilde;o 3</a></li>
          <li><a href="#">Op&ccedil;&atilde;o 4</a></li>
          <li><a href="#">Op&ccedil;&atilde;o 5</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sub-menu <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Op&ccedil;&atilde;o 1</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">T&iacute;tulo</li>
                <li><a href="#">Op&ccedil;&atilde;o 2</a></li>
                <li><a href="#">Op&ccedil;&atilde;o 3</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
   </div>